[package]
name = "kernel_emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
elf_rs = "0.2.0"
syscalls = { version = "0.5.0", default-features = false }
thiserror = "1.0.30"
yaxpeax-x86 = "1.1.4"
yaxpeax-arch = "0.2.7"
segmap = "0.1.0"
unicorn-engine = "2.0.0-rc6"
