[package]
name = "kernel_emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
unicorn-engine = "2.0.0-rc6"
elf_rs = "0.2.0"
syscalls = { version = "0.5.0", default-features = false }
thiserror = "1.0.30"